---
- name: update web, nfs, and db servers
  hosts: webservers, nfs, db
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

    - name: create a directory and a file inside it
      file:
        path: /home/devOps
        state: directory
        mode: 0755

    - name: create a file inside the directory
      file:
        path: /home/devOps/playbook.yml
        state: touch
        mode: 0644

    - name: change timezone on all servers
      timezone:
        name: Africa/Lagos

    - name: Create shell script file
      copy:
        content: |
          #!/bin/bash
          echo "Current date is $(date +%Y-%m-%d)"
        dest: /home/script.sh
        mode: '0755'

    - name: Run shell script
      shell: /home/script.sh
      register: current_date

    - name: Display output
      debug:
        var: current_date.stdout

